Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.9/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt

def my_g(x):
    return np.exp(-x)*np.cos(x)
    
x = np.linspace(-2.0,2.0, num=100)
plt.plot(x, my_g(x))
plt.plot(x, x)
plt.axhline(0, color='black')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 6[0m
[1;32m      3[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mmy_g[39m(x):
[1;32m      4[0m     [38;5;28;01mreturn[39;00m np[38;5;241m.[39mexp([38;5;241m-[39mx)[38;5;241m*[39mnp[38;5;241m.[39mcos(x)
[0;32m----> 6[0m x [38;5;241m=[39m [43mnp[49m[38;5;241m.[39mlinspace([38;5;241m-[39m[38;5;241m2.0[39m,[38;5;241m2.0[39m, num[38;5;241m=[39m[38;5;241m100[39m)
[1;32m      7[0m plt[38;5;241m.[39mplot(x, my_g(x))
[1;32m      8[0m plt[38;5;241m.[39mplot(x, x)

[0;31mNameError[0m: name 'np' is not defined

